language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "MH6grXmrZTybyyHMfmiGezix9WIX2y8CDNTI0jB161bQKNbeNJ7T+VINKlvRztEwjNat5aUBENVYZuPnsh+eru9k3zO9oDiZt95tdMXjLjuAHrmqlLtJFt1XIkNBLCJz6jVxQNGSW+6UaVLfhlvXs6HbDh+6PiW5UdHq/oiZmzOhjFo8z6e37MFafS2WbpG2q7YfJ6A4wE9yYxLJRAQdotsxFpxEG2UOC7/kTMgNzKQzsYipqmd2+n69N502tt9RF89Tx2d/Zrt661sGAKubP9H2hqbeAcxEBYaINovEicZKq42/r9ThBbYb86298ce+X4+JMq1fIer++HTV7ZiM0vavmjqgfVKeeWLsv12WtchPts0r5ZSnlK6pJc5FO5+EsPK7wKnFs1pImnP1oeqIVVA9mJTbSFEhHPaQAy1QaiM3NDFdwEUXBzHX0lp/kijDKwPA0Zrg31pGm1NeYi6a9uEi4Y1DtUlYFkvL9MXihENkgptAkoPFnFkt2y+A63y08pgtCe4SDW+/030h+1NEvwq55ozbSWj6P5dexEhVDqN88VyBqMprZeKBjgf8GywV4RIokZ87RXSwo5gb6hlXvRnOZMXsU1glrMwEY2olDueXDKQ9Lv+QcNjAMXnsnqOo+v/Suas65ra7dQDHvWL0GvCH3BRLWuUwuojXY+GzQT0="
