language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "JEWmTTYCSdDAiwlkcr/YKZfZYutOSBT9cVupoSbhsvVeANxWOycCtaWycH3UWg7EOWxcx8DXRJit9D1vZzOCwa9v23o4xpUqvqfQMlXyAHNnCk5LlEYtijCb7En7jAuo4aiS45YnbnwQt709BWHJ2d+PParZwLMW52FbzWK9tfl2TE6mWFSK/9JOejFAX7kx8r4oMhZwYwaP6QETnFUHdzLhcQUBhsn1C5qghhDvnbkK6Bgfaj+CdUjjLsdY2gQJrp8cJpCOHsJbCqy0C0TSZoljkbXP6rRAI4o4UbtHKzeog+qYnNiMxR1TPQEQIlsUfK9hHzNExRP+MWcvjCNJs5k+e6J+cnnzvDx7ftcgZII4uob9TBdfvhtC5Hmd81hJAa29bjx8/iZkY8estKugThThGNpDfwQ9IQiUgk00LGa3G+nvDbUkKk+5uJBSFdMld3E0o1pCQxiV6Te95cONhGg51zg0lCuEN2fhhdF/tNgB/jwNI06J92DJRhon9b7+sXhZuoL7Pb2OAey7DD7Lfe5b4Id5usBz5lKUkpQ4yGyca/JuF12ZFOYezNeA/e1YwW3JU/C3WYXh1FXR38KXXnX/bjPU6QsFqWp+0TU1XCYRWRe5SJDv2x0cvgnLtIUThzqu3yByX2HcspsI4YpO/MRDIH2Yp2JlWKHragOQevA="
env:
  secure: "q4cT2u63je4RfXBYAjyh5dLnapd4EF487agcWmh9MPJA11+r2nOiPX8kynfM8NrIA0+IvQ7wdgEvMT2MGm68F8LJ9pQf9fKZb5XSBCdE2/yCdnY5opYEgfxQXoErNMkuVgcdT/IIg2S/6JrijxoJmPHwB8Ef6G0XA0rR/G+v4ZjU+d8hFDlQE1bvc4V5mTHFXCRQ7t7hNf3ZbVNGe+gPuF53c3YjK3V/r8sa0prIA8YDgZVUxVTwyAYwSiBdhVM/yw1OHwiKS4X97/qKozztoI/+QJDoYVerFnAWTrULr8wbgPeavM3ZgAp9hLiJZqn/9eo6IPHyq6/lFB9ezhrxVH5NzHL31Y3OMcsLLklPLB3jBXbg7qY3YigQoropQ5W00j78BSTVsvIs7kMkUHwEL8cUvfo6ml6/b8ATqafvrbpoXarvYPamFZ/X5e+4d0T/xuu8NLq/cnx2ryyctm5HX/UqyyxnHJAumdfvofa9J1vDjwz8R4PTRw1drzgVUHx+3Y5OyAEv83WBnqs1GbiORn3w2vs72FvCYYxZIGa/m+RzMFLEhOKTd5IRr0jCtoCM1BxVC5Gx/M5TzXztslreQjYHO7Z+Wcuf6BphO2v0ZkMsFJhlZYoGV8rELU5NMkl2c0eZri1OXtKLgREimdSV8prlK3UMh8MbpRr3RXQZpMw="
