language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "gzWpB3hVa2mB9clU3o1faBo/JEcFlUqWOCxN6ElwFhA/XT1fMbqgMvG6nE8XDxcs+we+39ChcUxf547sqAvGVD54Z0pgg1X35ohzlkO6QBXKZy7gy1H5QGNyyu17gqinLoD0FxTYXVsCiVuN7y2jqrfxhYQ6/69u03j9R6jJLSxB6uTuONBfNNf/vrf4jOeLaZPLqEBat4bY7OYKMLjv4AkKq0EPrFG2l5MhqIzUq9i/6EVFFEiJ5z3putXF4+pllaEgyOfKKjG1WP8MniXnAn6hdvgVbZf4Kf2uBS52mHQpVQYDe3TBW6WFdLLRq8CZ6JDU5Zga9lbXm87gg6gA5aKCbMj6Y5f3VA9EZK3rVXL4IfCPyU6zQOyqeiYGFcLKxQvUZKC7tBQiOk2O5nspd1F8bCytvVp/828aRQcdKaPi7O+E3ZjNdR9BQg9J3mgP/EWNtAOvOs9F2bnOD0hkTxz/UP03yFUT+J5JgQQC/Xf+vooMNlQRApEOdguKPiyHtUZSEdxlCaUVexHg269o7/Gz0v2YHq4NHg8mhVi7q3p2MCYF0lVWntXaN7uv0U/w/7SCBgwavozWOF6FGdxrSBhYPMraedoHqgaHVXrlaQAXVhElOG+/VCx9WQ6gYE3PV5c5xUgLG5R4ruoVkQgzuN8/EjiRmhsBQY+7/PSaYFQ="
